
#spring:
#    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://mysql.sqlpub.com:3306/selabspringe
#        username: neoabridges
#        password: 86bc514d3780ac7e
server:
  port: 1234
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:

    uri-encoding: utf-8
  #port: 21603


spring:

  servlet:
    multipart:
      max-file-size: 31457280          # 30MB
      max-request-size: 31457280
  application:
    name: demo
  datasource:
    hikari:
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.sqlpub.com:3306/selabspringe
    username: neoabridges
    password: 86bc514d3780ac7e
mybatis:
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler


